### PR TITLE
Merge unreleased now only merges project-specific changes into each project.

### LINKED ISSUE #569: Merge unreleased applies all changes to all projects
**Description**
"merge unreleased" (#518) does not support projects correctly.

**Reproduction Steps**
1. Set up changie with projects configured
2. Add some unreleased changes specific to each project
3. Run `changie merge -u "unreleased"`

**What happened**
Every changelog has all unreleased changes.

**Expected behavior**
Only changes specific to a project should be added as unreleased changes in that project's changelog.

**Additional context**
This feature is very handy for monorepos - I was about to request it before I realised it was already an option - because not all projects in the monorepo have unreleased changes at the same time. I want to verify in CI that unreleased changie files are valid, and `changie batch` fails on projects without changes.

Perhaps broken during #557, when merge switched from per-project to all projects.

### PR DESCRIPTION
**Pull request by TheSpyder**
Closes #569

**Check the following**
- [x] Keep 100% code coverage
- [x] Be properly formatted
- [x] ~Documentation changes are included~
- [x] Include a change file if expected

**Additional context**
The fix was so easy I decided to try my hand at my first PR in go 😅 

The test I deleted was negated by #557, it's no longer possible to pass an invalid project to merge (since projects can't be passed at all). But when trying to write a test for this fix it confused me and made the process take longer than it should've - so I deleted it. Hope that's ok.

### CODE REVIEW

**Comment by miniscruff** [comment]
Good find, just need to run the formatter and that should be all

**Comment by TheSpyder** [comment]
Yeah I didn't remember to run the linter before opening the PR 🫣

**Comment by TheSpyder** [comment]
Interestingly `make lint` didn't fail on my test, it complains about `core/utils_test.go`. I had to run `gofmt -s -w` on each file I changed to figure out what was wrong.

**Comment by TheSpyder** [comment]
hmm, it seems the test I deleted was counting for some code coverage. Should I put it back?

**Comment by miniscruff** [comment]
> Interestingly `make lint` didn't fail on my test, it complains about `core/utils_test.go`. I had to run `gofmt -s -w` on each file I changed to figure out what was wrong.

Hmm weird, I will take a look at the scripts to see why

**Comment by miniscruff** [comment]
> hmm, it seems the test I deleted was counting for some code coverage. Should I put it back?

Yea, it's testing that one of the projects is configured wrong because the changelog path doesn't exist.

**Comment by TheSpyder** [comment]
> Yea, it's testing that one of the projects is configured wrong because the changelog path doesn't exist

That's where the code is no longer covered, but the test is titled "invalid project" which is no longer necessary after the project config was removed. That's why I deleted it.
https://github.com/miniscruff/changie/pull/557/files#diff-fb89a4765053f1ffc1543a1d170f07c7da15bf932610ba3e67a186d1cc051c03L129

Mind if I rename it when I bring it back?

**Comment by miniscruff** [comment]
> > Yea, it's testing that one of the projects is configured wrong because the changelog path doesn't exist
> 
> That's where the code is no longer covered, but the test is titled "invalid project" which is no longer necessary after the project config was removed. That's why I deleted it.
> https://github.com/miniscruff/changie/pull/557/files#diff-fb89a4765053f1ffc1543a1d170f07c7da15bf932610ba3e67a186d1cc051c03L129
> 
> Mind if I rename it when I bring it back?

Yea I think more specifically it's an invalid project config. So probably worth a rename.

**Comment by TheSpyder** [comment]
🤨 
```
[2023-10-30T04:33:12.656Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/)
Error: There was an error fetching the storage URL during POST: 404 -
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

**Comment by miniscruff** [comment]
> 🤨 
> ```
> [2023-10-30T04:33:12.656Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/)
> Error: There was an error fetching the storage URL during POST: 404 -
> {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
> ```

Usually I just retry it when this happens, never figured out why though.

**Comment by miniscruff** [comment]
I am going to quickly do a batch+merge ( kinda want to make an action for this ) to rollout the fix asap, thanks again.

**Review by miniscruff — APPROVED** [review]

**Comment by TheSpyder** [comment]
I'm starting to see a need for batch+merge myself, also some sort of equivalent to `merge -u` for batch in monorepos. I might start a ticket or discussion for that soon 🤔

**Comment by miniscruff** [comment]
I was thinking some comment based GitHub actions to run some stuff. Not sure yet.

**Pull request merged**
