### PR TITLE
add ability to reference previous version in versionFormat template

### LINKED ISSUE #225: Allow for accessing "Previous Version" in versionFormat
**Is your feature request related to a problem? Please describe.**
I would like to use a custom version format that allows the version header be a link to the changes

```yaml
versionFormat: '## [{{.Version}}](https://github.com/miniscruff/changie/compare/{{.PreviousVersion}}...{{.Version}})'
```

So it would emit the markdown

```
## [v0.2.0](https://github.com/miniscruff/changie/compare/v0.1.0...v0.2.0) 
```

**Describe the solution you'd like**
It should be as simple as pipeing the "current version" of the batch command before increment as one of the valid batchData things.

**Describe alternatives you've considered**
It seems pretty straightforward ask so I had not considered anything things since the syntax for the formatting requires the previous version

### PR DESCRIPTION
**Pull request by rocktavious**
Closes #225

**Check the following**
- [ ] Keep 100% code coverage
- [ ] Be properly formatted
- [ ] Have no linting errors
- [ ] Documentation changes are included
- [ ] Include a change file if expected

**Additional context**
Any additional info that might help get your pull request merged.

### CODE REVIEW

**Comment by miniscruff** [comment]
> @miniscruff - Here is the kind of change i'm thinking of for #225
> 
> I added a test for the code I added but its only 99.6% - Any advice on what other tests I should add to get back to 100% would be helpful Thanks!

`make coverage` will create an html output for code coverage and you can see the missing line.

**Comment by miniscruff** [comment]
I like the idea and will definitely get this in the next release, however, I am currently rewriting the batch and batch test files so I won't be able to approve this PR but I will definitely copy paste some of it. I will keep the PR open until my next refactor commit. Hopefully in the next day or two the batch command will be a lot easier to read, understand and expand.

**Comment by rocktavious** [comment]
@miniscruff - awesome!

**Comment by miniscruff** [comment]
Closing in favor of #227 please comment there if I missed anything

**Pull request closed without merging**
