### PR TITLE
Add NPM distribution

### LINKED ISSUE #561: NPM distribution
As a JavaScript developer, I'd like to use changie but it's not available as a peer of other JavaScript tooling through NPM. JavaScript projects generally only require `npm` to be installed on the system, everything else (even binary executables) are installed through NPM packages.

### Transferred from https://github.com/miniscruff/changie/discussions/550

Where we've landed in the discussion is I will contribute some JS scripts and initial config. The bulk of this task is adding a step to `release.yml` that collects the archive binaries for distribution. To keep the size of the npm package down, I'm going to exclude the `386` builds and just ship the 6 major OS/Arch combinations:

* `dist/changie_darwin_arm64/changie`
* `dist/changie_darwin_amd64_v1/changie`
* `dist/changie_linux_arm64/changie`
* `dist/changie_linux_amd64_v1/changie`
* `dist/changie_windows_arm64/changie.exe`
* `dist/changie_windows_amd64_v1/changie.exe`

To achieve this, I need to do a few things.
* create a script to parse `dist/artifacts.json` and collect the required binaries (the paths above cannot be relied on)
* Execute this script after the `Run GoReleaser` step in the release github action
* Add a `package.json` and include it to the list of replacements in `.changie.yaml` config
* Use the [NodeJS github action](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry) to publish changie

### PR DESCRIPTION
**Pull request by TheSpyder**
Closes #561

**Check the following**
- [x] Keep 100% code coverage
- [x] Be properly formatted
- [x] Documentation changes are included
- [x] Include a change file if expected

### CODE REVIEW

**Comment by miniscruff** [comment]
https://www.npmjs.com/package/changie ran the commands locally and published the package, the npx and install commands seem to be working for me on linux, not sure if you want to give this a try before I merge it.

**Comment by TheSpyder** [comment]
yes, that works - sorry, it took a while to install from Australia as it hadn't reached the CDN end nodes yet 😅

**Comment by miniscruff** [comment]
> yes, that works - sorry, it took a while to install from Australia as it hadn't reached the CDN end nodes yet 😅

haha, that explains the timing of all your comments :smirk:

Alright, lets see how this goes. :laughing:

**Comment by TheSpyder** [comment]
hehe yeah I'm sure some of my activity is at weird hours for you 😆 

I don't think it's a _huge_ problem, but you seem to have used the `main` branch to build and release that rather than the 1.14 tag. This build includes the swap from `changie merge --project` to auto-merging all projects.

**Comment by miniscruff** [comment]
> hehe yeah I'm sure some of my activity is at weird hours for you 😆
> 
> I don't think it's a _huge_ problem, but you seem to have used the `main` branch to build and release that rather than the 1.14 tag. This build includes the swap from `changie merge --project` to auto-merging all projects.

oh yea... let me delete v1.14 from NPM as its not accurate then.

**Comment by miniscruff** [comment]
@TheSpyder ok it seems like v1.15.0 is up on NPM properly with your auto deployment. Had some issues with winget but all good for now, will have to come back to that one later.

**Comment by TheSpyder** [comment]
Ah yeah NPM doesn't really support deleting versions, the closest they have is [deprecate](https://docs.npmjs.com/cli/v7/commands/npm-deprecate)

But nobody is using it yet so I'm sure they won't notice 🙂

**Pull request merged**
