### PR TITLE
Add ability to apply templating to header & footer files

### LINKED ISSUE #230: Create header and footer template values to add an additional option for batch outputs
This will make the order of batching:
1. version header
2. header files ( cli arg and config )
3. header template
4. change templates
5. footer template
6. footer files ( cli arg and config )

Not sure on what to pass into these templates yet for data but probably version, previous version, time, [] changes for now

### PR DESCRIPTION
**Pull request by rocktavious**
Closes #230

**Check the following**
- [ ] Keep 100% code coverage
- [ ] Be properly formatted
- [ ] Have no linting errors
- [ ] Documentation changes are included
- [ ] Include a change file if expected

**Additional context**
This is based on PR #232 and as such includes its changes.

@miniscruff - Here is my take on how to close 230.  I'm open to any feedback you have.  The tests will NOT pass because I changed the signature of BatchPipeliner interface to make this work.  I'm happy to fix up the tests and adjust the documentations if you think this change is the right way to go about doing this.

IMO this allows the for the most flexibility on the end user's part because the header and footer can just be plain files OR they can be templates AND allows it to be configured as ephmeral or persistent.  This also means we could do a follow on which adds a new flag & config `body-path` / `bodyFormat` which could allow for the batch body to be completely built up using a template too for maximum flexibility for a power user to fully leverage sprig templates.

Also then going 1 step further we could completely remove the `BatchPipeliner.WriteChanges` function by converting it's logic to the default bodyFormat by leveraging sprig to provide as an example of how powerful and configurable the template format can be.

### CODE REVIEW

**Comment by miniscruff** [comment]
> Also then going 1 step further we could completely remove the `BatchPipeliner.WriteChanges` function by converting it's logic to the default bodyFormat by leveraging sprig to provide as an example of how powerful and configurable the template format can be.

I think this sounds interesting but I am a little hesitant to go all in on sprig just yet, I would like to try it out a bit and see how it goes.

**Comment by miniscruff** [comment]
I think this looks good. Obviously some tests are gonna fail and probably linting issues, will definitely need some doc updates as well. I can help out with any of that if you are busy as well, but yea no complaints on the code really.

**Comment by rocktavious** [comment]
Alright @miniscruff - I fixed up the tests and got to a passing state locally but its only 
```
ok  	github.com/miniscruff/changie/cmd	3.406s	coverage: 99.3% of statements
```

Would love any help with getting that back to 100% for you but i'm not sure what to do.

**Comment by miniscruff** [comment]
> Alright @miniscruff - I fixed up the tests and got to a passing state locally but its only
> 
> ```
> ok  	github.com/miniscruff/changie/cmd	3.406s	coverage: 99.3% of statements
> ```
> 
> Would love any help with getting that back to 100% for you but i'm not sure what to do.

If you fix linting I can get that last little bit, or run `make coverage` and look at the html for the missing line. We also should mention in the docs that templates have extra functions.

**Comment by miniscruff** [comment]
Moved the work over to #239 as I was not able to work directly from the branch. Will probably get it done tomorrow.

**Pull request closed without merging**
